### PR TITLE
Data Refactor / Programmatically Merging Nested Data

### PR DESCRIPTION
**Pull request by brickman1444**
Refactor the internals of census_response to use a new GCFDData type that should more easily support combining different data sources into one object and then outputting dump style and merge style JSON files.

I was able to use the census tests to verify that I didn't break existing behavior. The expected output for the poverty tests had to be updated to remove race data that accidentally added in because the census data was previously all held in a global object

I think there are a lot of further refactors that could be done in census response (optimization of dataframe operations, reduce duplicated code, change expected census test output to pretty printed, etc) but I want to get this pull request submitted since this is the bulk of the change and currently works correctly.

We'll have to follow up this change with actually bubbling up the GCFDData to main.py and combining the data at that level and then writing the combined data to file at the end.

Questions:
 * Should we try to add support for reading and writing GCFDData to pickle files in this pull request too or add that in a separate pull request?
 * I had called GCFDData "Wrapper" at one point so I have a lot of local variables named "wrapper". Is there a better name for those? gcfd_data?

### CODE REVIEW

**Comment by michaelpkuhn** [comment]
>     * Should we try to add support for reading and writing GCFDData to pickle files in this pull request too or add that in a separate pull request?

We could do that in a separate one. I'd like to pickle each DataFrame so it can be easily retrieved with the same typing.

**Comment by michaelpkuhn** [comment]
>     * I had called GCFDData "Wrapper" at one point so I have a lot of local variables named "wrapper". Is there a better name for those? gcfd_data?

Could call the variables `w` with a comment indicating it's a wrapper; `_wrapper`; `temp`

**Comment by michaelpkuhn** [comment]
> We'll have to follow up this change with actually bubbling up the GCFDData to main.py and combining the data at that level and then writing the combined data to file at the end.

Where is this done now?

**Comment by brickman1444** [comment]
> > We'll have to follow up this change with actually bubbling up the GCFDData to main.py and combining the data at that level and then writing the combined data to file at the end.
> 
> Where is this done now?

Census_response.py writes the census data to json files and then in main.py we call src.wic.merge_wic_data_file() and merge_ins_data() to read the files in, merge it with the new data and write it back to file. Hopefully after this change it'll be easy to do all that in memory and just write files at the end.

**Review by StephenWoo — APPROVED** [review]

**Review by michaelpkuhn — CHANGES_REQUESTED** [review]

**Review by michaelpkuhn — APPROVED** [review]

**Pull request merged**
